### ISSUE TITLE
Set chmod and chown with an explicit version

### ISSUE THREAD

**Issue by KirmTwinty** [datakortet/yamldirs#6]
Hi!
I needed a more convenient way to define directories and files, and particularly being able to set their mode/user/group.
As a consequence, I took your library and created a new class called "FilemakerExplicit" and added an option (--explicit-version) to the CLI. It only work in one way though (`YAML` to directories, not the other one for now).

Here is an example:
``` yaml
directory: my_directory
children:
  - file: myfile
    content: |
      Some content
      for the file
  - file: myfile2
    content: |
      Some content for
      another file
    user: games
  - directory: my_directory2
    mode: 0o777
    children:
      - myfile3
```

Maybe this can be useful to someone else? If so, I can do a PR.

Checkout my branch: [feature/chmod-chown-keywords](https://github.com/KirmTwinty/yamldirs/tree/feature/chmod-chown-keywords)
